### ISSUE TITLE
Select parts of loaded file as data

### ISSUE THREAD

**Issue by janbrohl** [sphinx-contrib/datatemplates#11]
Introduce a new option (eg `:path:`) to select parts within file via [XPath](https://docs.python.org/3/library/xml.etree.elementtree.html#xpath-support) for XML or [JSON Pointer](https://pypi.org/project/jsonpointer/) for other formats.

**Comment by dhellmann** [comment]
So rather than the template needing to know about the full structure of the data, this would pass only part of the data to it?

I wonder if we need to worry about someone mistakenly using different selection variants with different formats (an XPath path value for a YAML file, for example)? Maybe we just use a different path parser for each file type, and if the input isn't supported that handles the validation.

**Comment by janbrohl** [comment]
This way a single Template can be used for data being differently nested or selecting just some elements instead of all. Eg using the same template for both XPaths `somelist/[@quality='good']`  and `somelist/[@quality='bad']`  but in different places.

Intepreting the same option differentily depending on file type would work fine if we use one directive for each file type. This way it would be clear to te user how the options are understood.

**Comment by dhellmann** [comment]
> This way a single Template can be used for data being differently nested or selecting just some elements instead of all. Eg using the same template for both XPaths `somelist/[@quality='good']` and `somelist/[@quality='bad']` but in different places.

That makes sense.

> Intepreting the same option differentily depending on file type would work fine if we use one directive for each file type. This way it would be clear to te user how the options are understood.

Do you mean to have a separate 'datatemplate' directive for XML data that has different options from the one for YAML data?

**Comment by dhellmann** [comment]
> > Intepreting the same option differentily depending on file type would work fine if we use one directive for each file type. This way it would be clear to te user how the options are understood.
> 
> Do you mean to have a separate 'datatemplate' directive for XML data that has different options from the one for YAML data?

I see from #17 that you do mean that. I think that does make some sense.

**Comment by janbrohl** [comment]
Actually, good support for JSON Pointer would add a dependency so I am not sure if it is worth it but (simple) XPath support is part of ElementTree. For CSV functionality like https://tools.ietf.org/html/rfc7111 should not be complicated to implement.

**Comment by janbrohl** [comment]
An alternative to this would be passing all options through to the template. This seems easier.

**Comment by dhellmann** [comment]
I like the approach in #45. Should we close this ticket as finished?

**Comment by janbrohl** [comment]
Yes.
