### ISSUE TITLE
Select loading mode via option

### ISSUE THREAD

**Issue by janbrohl** [sphinx-contrib/datatemplates#12]
Add new option (eg `:mode:`) for sellect how the file should be loaded instead of guessing based on analyzing the path from `:source:`.

Where this would help:
- There are many XML based formats and some of them cannot easily be guessed from the filename.
- YAML files can contain multiple documents.
- No extra option needed for selecting CSV reader.
- Adds extensible mechanism to add more loaders (eg glob, url)

**Comment by janbrohl** [comment]
Now I think, adding separate options to change how data is loaded is easier to understand and easier to document.

**Comment by dhellmann** [comment]
I think the separate directives probably resolves this one? Unless you want to reframe it to be about the extension mechanism?

**Comment by dhellmann** [comment]
Is this related to #40 as well?

**Comment by janbrohl** [comment]
More to #49 but I'll open a new issue for the extension mechanism.
