### ISSUE TITLE
Share code between CLI tool and directives?

### ISSUE THREAD

**Issue by janbrohl** [sphinx-contrib/datatemplates#21]
Although much of the directives' logic is not useful for the CLI tool, some is shared.
Is it worth the effort to bring both together?

**Comment by dhellmann** [comment]
Maybe? I probably just threw the CLI together without thinking about that very much. Now that you're refactoring the directive to allow subclasses for different types I think it's likely worth revisiting.

**Comment by dhellmann** [comment]
I think we can probably close this as done. If there was some other work you planned, please re-open.
