### ISSUE TITLE
Mention CLI in docs

### ISSUE THREAD

**Issue by cdeil** [sphinx-contrib/datatemplates#3]
I think this package is just what I need. I'll try it out now. Thank you very much!

I just saw https://github.com/dhellmann/sphinxcontrib.datatemplates/commit/f2d114a5813210c8c834d679f4517a1210136ddc by chance. Could you please mention the CLI tool in the docs?

**Comment by cdeil** [comment]
The name `test-template` is very generic to put on people's PATH, no?
Maybe choose a more explicit name like `sphinx-datatemplates-test`, that has the project name and people more easily find out what it is?

**Comment by dhellmann** [comment]
The CLI is listed in the docs now https://sphinxcontribdatatemplates.readthedocs.io/en/latest/cli.html
