### ISSUE TITLE
Declare compatibility with older dependencies

### ISSUE THREAD

**Issue by janbrohl** [sphinx-contrib/datatemplates#31]
There still are people building docs with Python 2.7 or 3.x as well as Sphinx 1.x eg. because of other extensions.
So it would be helpful for them to state compatible versions somewhere.

**Comment by dhellmann** [comment]
I'm comfortable with dropping python 2 support as part of releasing 1.0. I think even the older releases only listed python 3 support.

**Comment by janbrohl** [comment]
That's allright for me, too.

**Comment by dhellmann** [comment]
OK, I'll close this wont fix then.
