### ISSUE TITLE
Use directive head?

### ISSUE THREAD

**Issue by janbrohl** [sphinx-contrib/datatemplates#34]
Not sure if that's the correct name but to me it would seem natural to use the part in the directive head for something like one of these:
- `.. datatemplate:json:: path/to/file.json`
- `.. datatemplate:json:: {"literal":"json"}`

**Comment by dhellmann** [comment]
Yeah, I think I looked at that way back at the beginning and thought being explicit would be easier to deal with. I'm definitely open to looking at it again, though, if you want to think through what makes the most sense.

Inlining a filename seems more useful to me, but should it be the data or the template?

**Comment by janbrohl** [comment]
This could complement #22 . This way no options would be needed for "normal" use.

**Comment by janbrohl** [comment]
Closed via #37
