### ISSUE TITLE
ModuleNotFoundError: No module named 'pbr'

### ISSUE THREAD

**Issue by ichihara-3** [sphinx-contrib/datatemplates#43]
Hi.

I installed datatemplates with `pip install sphinxcontrib.datatemplates==0.5.0` 
When using datatemplates.helpers in a script, `ModuleNotFoundError: No module named 'pbr'` occured.

In a script ::

```
    from sphinxcontrib.datatemplates import helpers
```
The error is caused when import statement is evaluated.

in REPL, also goes to an error.
```
>>> from sphinxcontrib.datatemplates import helpers
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/virtualenvs/docs2/lib/python3.6/site-packages/sphinxcontrib/datatemplates/__init__.py", line 1, in <module>
    import pbr.version
ModuleNotFoundError: No module named 'pbr'
```

versions::
Ubuntu 18.04
Python3.6.9
Sphinx 2.2.0
datatemplates 0.5.0

**Comment by janbrohl** [comment]
Thank you for your feedback.
This problem should be fixed in newly released version 0.6.1 .
